[[listvalue]]
pkg = "com.sheneternity"
name = "ShenEternity"
mode = "balance"
[[listvalue]]
pkg = "com.sheneternity"
name = "ShenEternity"
[[listvalue]]
pkg = "com.sheneternity"
name = "ShenEternity"
